// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: stubs/common/v1/common.proto

// 包名定义，用于避免命名冲突

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_stubs_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_stubs_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stubs_common_v1_common_proto protoreflect.FileDescriptor

const file_stubs_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cstubs/common/v1/common.proto\x12\tcommon.v1\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB?Z=github.com/yixin8875/ai-grpc-go-client/stubs/common/v1;commonb\x06proto3"

var (
	file_stubs_common_v1_common_proto_rawDescOnce sync.Once
	file_stubs_common_v1_common_proto_rawDescData []byte
)

func file_stubs_common_v1_common_proto_rawDescGZIP() []byte {
	file_stubs_common_v1_common_proto_rawDescOnce.Do(func() {
		file_stubs_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stubs_common_v1_common_proto_rawDesc), len(file_stubs_common_v1_common_proto_rawDesc)))
	})
	return file_stubs_common_v1_common_proto_rawDescData
}

var file_stubs_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stubs_common_v1_common_proto_goTypes = []any{
	(*Error)(nil), // 0: common.v1.Error
}
var file_stubs_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stubs_common_v1_common_proto_init() }
func file_stubs_common_v1_common_proto_init() {
	if File_stubs_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stubs_common_v1_common_proto_rawDesc), len(file_stubs_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stubs_common_v1_common_proto_goTypes,
		DependencyIndexes: file_stubs_common_v1_common_proto_depIdxs,
		MessageInfos:      file_stubs_common_v1_common_proto_msgTypes,
	}.Build()
	File_stubs_common_v1_common_proto = out.File
	file_stubs_common_v1_common_proto_goTypes = nil
	file_stubs_common_v1_common_proto_depIdxs = nil
}
