// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: stubs/aibot/services/v1/agent.proto

// 定义 Protobuf 包名

package agent

import (
	v1 "ai_grpc_go_client/stubs/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 从Go发往Python的事件
type UserEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserInput      string                 `protobuf:"bytes,2,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UserEvent) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

// 从Python流式返回给Go的事件
type AIResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*AIResponse_StatusUpdate
	//	*AIResponse_PlanGenerated
	//	*AIResponse_StepStateChange
	//	*AIResponse_StepExecutingContent
	//	*AIResponse_UserPrompt
	//	*AIResponse_FinalResult
	//	*AIResponse_Error
	Event         isAIResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIResponse) Reset() {
	*x = AIResponse{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIResponse) ProtoMessage() {}

func (x *AIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIResponse.ProtoReflect.Descriptor instead.
func (*AIResponse) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AIResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AIResponse) GetEvent() isAIResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AIResponse) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *AIResponse) GetPlanGenerated() *PlanGenerated {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_PlanGenerated); ok {
			return x.PlanGenerated
		}
	}
	return nil
}

func (x *AIResponse) GetStepStateChange() *StepStateChange {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_StepStateChange); ok {
			return x.StepStateChange
		}
	}
	return nil
}

func (x *AIResponse) GetStepExecutingContent() *StepExecutingContent {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_StepExecutingContent); ok {
			return x.StepExecutingContent
		}
	}
	return nil
}

func (x *AIResponse) GetUserPrompt() *UserPrompt {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_UserPrompt); ok {
			return x.UserPrompt
		}
	}
	return nil
}

func (x *AIResponse) GetFinalResult() *FinalResult {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_FinalResult); ok {
			return x.FinalResult
		}
	}
	return nil
}

func (x *AIResponse) GetError() *v1.Error {
	if x != nil {
		if x, ok := x.Event.(*AIResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAIResponse_Event interface {
	isAIResponse_Event()
}

type AIResponse_StatusUpdate struct {
	StatusUpdate *StatusUpdate `protobuf:"bytes,2,opt,name=status_update,json=statusUpdate,proto3,oneof"` // 状态更新，如"正在思考..."
}

type AIResponse_PlanGenerated struct {
	PlanGenerated *PlanGenerated `protobuf:"bytes,3,opt,name=plan_generated,json=planGenerated,proto3,oneof"` // 计划已生成
}

type AIResponse_StepStateChange struct {
	StepStateChange *StepStateChange `protobuf:"bytes,4,opt,name=step_state_change,json=stepStateChange,proto3,oneof"` // 步骤状态变化 (开始/完成)
}

type AIResponse_StepExecutingContent struct {
	StepExecutingContent *StepExecutingContent `protobuf:"bytes,5,opt,name=step_executing_content,json=stepExecutingContent,proto3,oneof"` // 步骤执行中产生的中间内容
}

type AIResponse_UserPrompt struct {
	UserPrompt *UserPrompt `protobuf:"bytes,6,opt,name=user_prompt,json=userPrompt,proto3,oneof"` // 需要用户输入
}

type AIResponse_FinalResult struct {
	FinalResult *FinalResult `protobuf:"bytes,7,opt,name=final_result,json=finalResult,proto3,oneof"` // 最终结果
}

type AIResponse_Error struct {
	Error *v1.Error `protobuf:"bytes,8,opt,name=error,proto3,oneof"` // 错误信息
}

func (*AIResponse_StatusUpdate) isAIResponse_Event() {}

func (*AIResponse_PlanGenerated) isAIResponse_Event() {}

func (*AIResponse_StepStateChange) isAIResponse_Event() {}

func (*AIResponse_StepExecutingContent) isAIResponse_Event() {}

func (*AIResponse_UserPrompt) isAIResponse_Event() {}

func (*AIResponse_FinalResult) isAIResponse_Event() {}

func (*AIResponse_Error) isAIResponse_Event() {}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "正在规划...", "正在执行..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "executing", "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Step) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Step) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Step) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PlanGenerated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Step                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanGenerated) Reset() {
	*x = PlanGenerated{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanGenerated) ProtoMessage() {}

func (x *PlanGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanGenerated.ProtoReflect.Descriptor instead.
func (*PlanGenerated) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PlanGenerated) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StepStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        int32                  `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "executing" or "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStateChange) Reset() {
	*x = StepStateChange{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStateChange) ProtoMessage() {}

func (x *StepStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStateChange.ProtoReflect.Descriptor instead.
func (*StepStateChange) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StepStateChange) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *StepStateChange) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StepExecutingContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForStepId     int32                  `protobuf:"varint,1,opt,name=for_step_id,json=forStepId,proto3" json:"for_step_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // AI执行这一步时的思考或结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecutingContent) Reset() {
	*x = StepExecutingContent{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecutingContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecutingContent) ProtoMessage() {}

func (x *StepExecutingContent) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecutingContent.ProtoReflect.Descriptor instead.
func (*StepExecutingContent) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StepExecutingContent) GetForStepId() int32 {
	if x != nil {
		return x.ForStepId
	}
	return 0
}

func (x *StepExecutingContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UserPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForStepId     int32                  `protobuf:"varint,1,opt,name=for_step_id,json=forStepId,proto3" json:"for_step_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	QuickReplies  []string               `protobuf:"bytes,3,rep,name=quick_replies,json=quickReplies,proto3" json:"quick_replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPrompt) Reset() {
	*x = UserPrompt{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrompt) ProtoMessage() {}

func (x *UserPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrompt.ProtoReflect.Descriptor instead.
func (*UserPrompt) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UserPrompt) GetForStepId() int32 {
	if x != nil {
		return x.ForStepId
	}
	return 0
}

func (x *UserPrompt) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UserPrompt) GetQuickReplies() []string {
	if x != nil {
		return x.QuickReplies
	}
	return nil
}

type FinalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResult) Reset() {
	*x = FinalResult{}
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResult) ProtoMessage() {}

func (x *FinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_aibot_services_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResult.ProtoReflect.Descriptor instead.
func (*FinalResult) Descriptor() ([]byte, []int) {
	return file_stubs_aibot_services_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FinalResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_stubs_aibot_services_v1_agent_proto protoreflect.FileDescriptor

const file_stubs_aibot_services_v1_agent_proto_rawDesc = "" +
	"\n" +
	"#stubs/aibot/services/v1/agent.proto\x12\x17aibot.services.agent.v1\x1a\x1cstubs/common/v1/common.proto\"S\n" +
	"\tUserEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x02 \x01(\tR\tuserInput\"\xd9\x04\n" +
	"\n" +
	"AIResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12L\n" +
	"\rstatus_update\x18\x02 \x01(\v2%.aibot.services.agent.v1.StatusUpdateH\x00R\fstatusUpdate\x12O\n" +
	"\x0eplan_generated\x18\x03 \x01(\v2&.aibot.services.agent.v1.PlanGeneratedH\x00R\rplanGenerated\x12V\n" +
	"\x11step_state_change\x18\x04 \x01(\v2(.aibot.services.agent.v1.StepStateChangeH\x00R\x0fstepStateChange\x12e\n" +
	"\x16step_executing_content\x18\x05 \x01(\v2-.aibot.services.agent.v1.StepExecutingContentH\x00R\x14stepExecutingContent\x12F\n" +
	"\vuser_prompt\x18\x06 \x01(\v2#.aibot.services.agent.v1.UserPromptH\x00R\n" +
	"userPrompt\x12I\n" +
	"\ffinal_result\x18\a \x01(\v2$.aibot.services.agent.v1.FinalResultH\x00R\vfinalResult\x12(\n" +
	"\x05error\x18\b \x01(\v2\x10.common.v1.ErrorH\x00R\x05errorB\a\n" +
	"\x05event\"(\n" +
	"\fStatusUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"D\n" +
	"\rPlanGenerated\x123\n" +
	"\x05steps\x18\x01 \x03(\v2\x1d.aibot.services.agent.v1.StepR\x05steps\"B\n" +
	"\x0fStepStateChange\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x05R\x06stepId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"P\n" +
	"\x14StepExecutingContent\x12\x1e\n" +
	"\vfor_step_id\x18\x01 \x01(\x05R\tforStepId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"m\n" +
	"\n" +
	"UserPrompt\x12\x1e\n" +
	"\vfor_step_id\x18\x01 \x01(\x05R\tforStepId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12#\n" +
	"\rquick_replies\x18\x03 \x03(\tR\fquickReplies\"'\n" +
	"\vFinalResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary2g\n" +
	"\fAgentService\x12W\n" +
	"\bConverse\x12\".aibot.services.agent.v1.UserEvent\x1a#.aibot.services.agent.v1.AIResponse(\x010\x01B1Z/ai_grpc_go_client/stubs/aibot/services/v1;agentb\x06proto3"

var (
	file_stubs_aibot_services_v1_agent_proto_rawDescOnce sync.Once
	file_stubs_aibot_services_v1_agent_proto_rawDescData []byte
)

func file_stubs_aibot_services_v1_agent_proto_rawDescGZIP() []byte {
	file_stubs_aibot_services_v1_agent_proto_rawDescOnce.Do(func() {
		file_stubs_aibot_services_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stubs_aibot_services_v1_agent_proto_rawDesc), len(file_stubs_aibot_services_v1_agent_proto_rawDesc)))
	})
	return file_stubs_aibot_services_v1_agent_proto_rawDescData
}

var file_stubs_aibot_services_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_stubs_aibot_services_v1_agent_proto_goTypes = []any{
	(*UserEvent)(nil),            // 0: aibot.services.agent.v1.UserEvent
	(*AIResponse)(nil),           // 1: aibot.services.agent.v1.AIResponse
	(*StatusUpdate)(nil),         // 2: aibot.services.agent.v1.StatusUpdate
	(*Step)(nil),                 // 3: aibot.services.agent.v1.Step
	(*PlanGenerated)(nil),        // 4: aibot.services.agent.v1.PlanGenerated
	(*StepStateChange)(nil),      // 5: aibot.services.agent.v1.StepStateChange
	(*StepExecutingContent)(nil), // 6: aibot.services.agent.v1.StepExecutingContent
	(*UserPrompt)(nil),           // 7: aibot.services.agent.v1.UserPrompt
	(*FinalResult)(nil),          // 8: aibot.services.agent.v1.FinalResult
	(*v1.Error)(nil),             // 9: common.v1.Error
}
var file_stubs_aibot_services_v1_agent_proto_depIdxs = []int32{
	2, // 0: aibot.services.agent.v1.AIResponse.status_update:type_name -> aibot.services.agent.v1.StatusUpdate
	4, // 1: aibot.services.agent.v1.AIResponse.plan_generated:type_name -> aibot.services.agent.v1.PlanGenerated
	5, // 2: aibot.services.agent.v1.AIResponse.step_state_change:type_name -> aibot.services.agent.v1.StepStateChange
	6, // 3: aibot.services.agent.v1.AIResponse.step_executing_content:type_name -> aibot.services.agent.v1.StepExecutingContent
	7, // 4: aibot.services.agent.v1.AIResponse.user_prompt:type_name -> aibot.services.agent.v1.UserPrompt
	8, // 5: aibot.services.agent.v1.AIResponse.final_result:type_name -> aibot.services.agent.v1.FinalResult
	9, // 6: aibot.services.agent.v1.AIResponse.error:type_name -> common.v1.Error
	3, // 7: aibot.services.agent.v1.PlanGenerated.steps:type_name -> aibot.services.agent.v1.Step
	0, // 8: aibot.services.agent.v1.AgentService.Converse:input_type -> aibot.services.agent.v1.UserEvent
	1, // 9: aibot.services.agent.v1.AgentService.Converse:output_type -> aibot.services.agent.v1.AIResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_stubs_aibot_services_v1_agent_proto_init() }
func file_stubs_aibot_services_v1_agent_proto_init() {
	if File_stubs_aibot_services_v1_agent_proto != nil {
		return
	}
	file_stubs_aibot_services_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AIResponse_StatusUpdate)(nil),
		(*AIResponse_PlanGenerated)(nil),
		(*AIResponse_StepStateChange)(nil),
		(*AIResponse_StepExecutingContent)(nil),
		(*AIResponse_UserPrompt)(nil),
		(*AIResponse_FinalResult)(nil),
		(*AIResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stubs_aibot_services_v1_agent_proto_rawDesc), len(file_stubs_aibot_services_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stubs_aibot_services_v1_agent_proto_goTypes,
		DependencyIndexes: file_stubs_aibot_services_v1_agent_proto_depIdxs,
		MessageInfos:      file_stubs_aibot_services_v1_agent_proto_msgTypes,
	}.Build()
	File_stubs_aibot_services_v1_agent_proto = out.File
	file_stubs_aibot_services_v1_agent_proto_goTypes = nil
	file_stubs_aibot_services_v1_agent_proto_depIdxs = nil
}
