// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: stubs/aibot/services/v1/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Converse 使用双向流，客户端发送用户事件，服务器流式返回AI响应
	Converse(ctx context.Context, opts ...grpc.CallOption) (AgentService_ConverseClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Converse(ctx context.Context, opts ...grpc.CallOption) (AgentService_ConverseClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/aibot.services.agent.v1.AgentService/Converse", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceConverseClient{stream}
	return x, nil
}

type AgentService_ConverseClient interface {
	Send(*UserEvent) error
	Recv() (*AIResponse, error)
	grpc.ClientStream
}

type agentServiceConverseClient struct {
	grpc.ClientStream
}

func (x *agentServiceConverseClient) Send(m *UserEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceConverseClient) Recv() (*AIResponse, error) {
	m := new(AIResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations should embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// Converse 使用双向流，客户端发送用户事件，服务器流式返回AI响应
	Converse(AgentService_ConverseServer) error
}

// UnimplementedAgentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Converse(AgentService_ConverseServer) error {
	return status.Errorf(codes.Unimplemented, "method Converse not implemented")
}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Converse(&agentServiceConverseServer{stream})
}

type AgentService_ConverseServer interface {
	Send(*AIResponse) error
	Recv() (*UserEvent, error)
	grpc.ServerStream
}

type agentServiceConverseServer struct {
	grpc.ServerStream
}

func (x *agentServiceConverseServer) Send(m *AIResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceConverseServer) Recv() (*UserEvent, error) {
	m := new(UserEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibot.services.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converse",
			Handler:       _AgentService_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stubs/aibot/services/v1/agent.proto",
}
